name: Lint Checkings
on:
  push:
    branches:
      - master
permissions: read-all
jobs:
  formatting-check:
    name: Clang Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - src
          - test
          - benchmark
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "16"
          check-path: ${{ matrix.path }}
