name: Testing Mega
on:
  push:
    branches:
      - master
permissions: read-all
jobs:
  test-mega:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the tests
        run: mkdir build && cd build && cmake .. && make -j
      - name: Run test
        run: cd build/test && ctest --output-on-failure -j$(nproc)
